version: "3.3"
services:
  rproxy:
    image: briansworth/nginx_rproxy:alpine
    build:
      context: ./Docker/
    env_file:
      - ./rproxy.env
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem 
    depends_on:
      - webtest

  webtest:
    image: briansworth/jekyll_demo:latest

